apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aro-thanos-blob-grafana-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aro-thanos-blob-grafana-cr
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aro-thanos-blob-grafana-cr
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadatasources
    verbs:
      - create
      - list
      - get
      - patch