apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aro-thanos-blob-af-creds
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: STORAGE-METRICS-YAML
      secretKey: store-secret.yaml
  secretStoreRef:
    kind: SecretStore
    name: aro-thanos-blob-store
  target:
    name: aro-thanos-blob-af-creds