apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aro-thanos-blob-store
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: azure.keyvault.client-id
          name: keyvault-serviceprincipal
        clientSecret:
          key: azure.keyvault.client-key
          name: keyvault-serviceprincipal
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: 14ca6bf4-a883-479e-bd9d-a73b7f590886
      vaultUrl: 'https://labs-aro-thanos.vault.azure.net/'