apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-metrics-persistance-operators
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster-config/operators
    repoURL: 'git@github.com:Ortec-Finance/orca-prometheus.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true