resources:
  - ../../base

components:
  - ../../components/azure-storage
  - ../../components/grafana

patches:
  - patch: |-
      - op: replace
        path: /spec/provider/azurekv/vaultUrl
        value: https://labs-temp-metric.vault.azure.net/
    target:
      group: external-secrets.io
      kind: SecretStore
      name: aro-thanos-blob-store
      version: v1beta1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: 'cluster="orca-pearl"'
    target:
      group: apps
      kind: StatefulSet
      name: thanos-receive
      version: v1