apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  labels:
    app.kubernetes.io/part-of: thanos-persistence
    app: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      serviceAccountName: aro-thanos-blob-thanos-querier
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.24.0-rc.2
        args:
        - query
        - --query.replica-label=replica
        # Discover local store APIs using DNS SRV.
        - --store=dnssrv+thanos-store-gateway.$(MY_POD_NAMESPACE).svc.cluster.local
        - --store=dns+thanos-receive.$(MY_POD_NAMESPACE).svc.cluster.local:19891
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http