apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    app.kubernetes.io/name: aro-thanos-af
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get