apiVersion: patch-operator.redhat.io/v1
kind: Patch
metadata:
  name: add-remote-write-to-user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
spec:
  targetRef:
    apiVersion: v1
    kind: ConfigMap
    name: user-workload-monitoring-config
    namespace: openshift-user-workload-monitoring
  patchType: merge
  patchContent: |
    data:
      config.yaml: |
        prometheus:
          remoteWrite:
            - url: "http://thanos-receive.cluster-metrics-persistance.svc.cluster.local:9091/api/v1/receive"
