apiVersion: v1
kind: ServiceAccount
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    app.kubernetes.io/name: aro-thanos-af
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    app.kubernetes.io/name: aro-thanos-af
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBidning
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    app.kubernetes.io/name: aro-thanos-af
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aro-thanos-af-grafana-agent
subjects:
- kind: ServiceAccount
  name: aro-thanos-af-grafana-agent