resources:
  - ../../../base

components:
  - ../../../components/azure-storage
  - ../../../components/grafana

images:
  - name: thanos-store
    newName: quay.io/thanos/thanos
    newTag: v0.24.0-rc.2
  - name: thanos-receive
    newName: quay.io/thanos/thanos
    newTag: v0.24.0-rc.2
  - name: thanos-querier
    newName: quay.io/thanos/thanos
    newTag: v0.24.0-rc.2
  - name: grafana-agent
    newName: grafana/agent
    newTag: v0.28.0
  - name: oc-cli
    newName: quay.io/openshift/origin-cli
    newTag: '4.11'
  - name: oc-oauth
    newName: quay.io/openshift/origin-oauth-proxy
    newTag: '4.11'

patches:
  - patch: |-
      - op: replace
        path: /spec/provider/azurekv/vaultUrl
        value: https://labs-temp-metric.vault.azure.net/
    target:
      group: external-secrets.io
      kind: SecretStore
      name: aro-thanos-blob-store
      version: v1beta1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: 'cluster="labs"'
    target:
      group: apps
      kind: StatefulSet
      name: thanos-receive
      version: v1