apiVersion: v1
kind: ServiceAccount
metadata:
  name: aro-thanos-af
  labels:
    app.kubernetes.io/name: aro-thanos-af
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: aro-thanos-af
  namespace: orca-prometheus