apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: aro-thanos-scc
priority: 10
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
