apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:cluster-metric-persistance:scc:aro-thanos
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - aro-thanos-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use