apiVersion: v1
kind: ServiceAccount
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    app.kubernetes.io/name: aro-thanos-af
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    helm.sh/chart: aro-thanos-af-0.5.0
    app.kubernetes.io/name: aro-thanos-af
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aro-thanos-af-grafana-agent
  labels:
    helm.sh/chart: aro-thanos-af-0.5.0
    app.kubernetes.io/name: aro-thanos-af
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aro-thanos-af-grafana-agent
subjects:
- kind: ServiceAccount
  name: aro-thanos-af-grafana-agent
  namespace: orca-prometheus