apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/part-of: thanos-persistence
    app: thanos-receive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app: thanos-receive
    spec:
      serviceAccountName: aro-thanos-blob
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: thanos-receive
        image: thanos-receive
        args:
        - receive
        - --tsdb.path=/data/remote-write-receive-data
        - --debug.name=receive
        - --log.level=info
        - --grpc-address=0.0.0.0:19891
        - --http-address=0.0.0.0:18091
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/prometheus/store-secret.yaml
        - '--receive.relabel-config-file=/etc/thanos/relabel-config.yaml'
        ports:
        - name: http
          containerPort: 19291
        - name: grpc
          containerPort: 19891
        volumeMounts:
        - name: store-credentials
          mountPath: /etc/prometheus/
          readOnly: true
        - name: remote-write-data
          mountPath: /data/remote-write-receive-data
        - name: relabel-config
          mountPath: /etc/thanos
          readOnly: true
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: "300m"
            memory: 5Gi

      volumes:
      - name: store-credentials
        secret:
          secretName: aro-thanos-blob-sa-creds
      - name: remote-write-data
        persistentVolumeClaim:
          claimName: thanos-receiver-pvc
      - name: relabel-config
        configMap:
          name: thanos-relabel-config