apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: add-remote-write-to-user-workload-monitoring-config
spec:
  serviceAccountRef:
    name: metric-persistance-patcher
  patches:
    remote-write:
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: user-workload-monitoring-config
        namespace: openshift-user-workload-monitoring
      patchType: application/merge-patch+json
      patchTemplate: |
        data:
          config.yaml: |
            prometheus:
              remoteWrite:
                - url: "http://thanos-receive.cluster-metrics-persistance.svc.cluster.local:9091/api/v1/receive"
