apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: add-remote-write-to-cluster-monitoring-config
spec:
  serviceAccountRef:
    name: metric-persistance-patcher
  patches:
    enable-user-workload:
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: cluster-monitoring-config
        namespace: openshift-monitoring
      patchType: application/merge-patch+json
      patchTemplate: |
        data:
          config.yaml: |
            alertmanagerMain: {}
            prometheusK8s: {}
            enableUserWorkload: true
