apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-persistance-patcher
  labels:
    app.kubernetes.io/name: metric-persistance-patcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-configmaps-clusterwide
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-configmaps-clusterwide
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-configmaps-clusterwide
subjects:
- kind: ServiceAccount
  name: metric-persistance-patcher
  namespace: cluster-metric-persistance