apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aro-thanos-blob
  namespace: openshift-gitops
spec:
  destination:
    namespace: 'aro-thanos-blob'
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/overlays/experimental
    repoURL: 'git@github.com:Ortec-Finance/orca-prometheus.git'
    targetRevision: renaming
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true