apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier
spec:
  ports:
  - port: 9091
    protocol: TCP
    name: web
  selector:
    app: thanos-querier
  type: ClusterIP