resources:
  - ../../../base

components:
  - ../../../components/azure-storage
  - ../../../components/grafana

patches:
  - patch: |-
      - op: replace
        path: /spec/provider/azurekv/vaultUrl
        value: https://labs-temp-metric.vault.azure.net/
    target:
      group: external-secrets.io
      kind: SecretStore
      name: aro-thanos-blob-store
      version: v1beta1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: 'cluster="dev"'
    target:
      group: apps
      kind: StatefulSet
      name: thanos-receive
      version: v1

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --store=dnssrv+thanos-store-gateway.experimental-cluster-connector.svc.cluster.local
    target:
      group: apps
      kind: Deployment
      name: thanos-querier
      version: v1