apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: aro-thanos-af-prometheus
  labels:

    app.kubernetes.io/name: aro-thanos-af
spec:
  name: aro-thanos-af.yaml
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: prometheus
      type: prometheus
      url: 'http://thanos-querier.orca-prometheus.svc.cluster.local:9090'
