apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: aro-thanos-af-grafana-cr
  labels:
    app.kubernetes.io/name: grafana-cr
spec:
  deployment:
    envFrom:
      - secretRef:
          name: grafana-secrets
  config:
    server:
      root_url: 'https://grafana-route-cluster-metrics-persistance.apps.gv4qq5qf.westeurope.aroapp.io'
    auth:
      disable_login_form:  true
      disable_signout_menu:  true
    auth.anonymous:
      enabled: false
    auth.generic_oauth:
      allow_sign_up:  true
      api_url: >-
        https://auth.ortec-finance.com/auth/realms/aro-platform_prd/protocol/openid-connect/userinfo
      auth_url: >-
        https://auth.ortec-finance.com/auth/realms/aro-platform_prd/protocol/openid-connect/auth
      enabled:  true
      token_url: >-
        https://auth.ortec-finance.com/auth/realms/aro-platform_prd/protocol/openid-connect/token
    log:
      level: debug
      mode: console
    users:
      auto_assign_org_role: Admin
  ingress:
    enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - { key: "app", operator: In, values: ['grafana'] }